# Server
spring.application.name=medication-management-system
server.port=8090

# Supabase Database - Transaction Pooling (Port 6543)
spring.datasource.url=jdbc:postgresql://aws-1-ap-northeast-1.pooler.supabase.com:6543/postgres?sslmode=require&prepareThreshold=0
spring.datasource.username=postgres.ejfdluooaqbnrappxnef
spring.datasource.password=DB_pass12345!@#$%
spring.datasource.driver-class-name=org.postgresql.Driver

# Connection Pool Settings for Transaction Pooling
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.max-lifetime=1800000

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

# Email configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=mocku730@gmail.com
spring.mail.password=kezawqmhkiqopfxd
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

test.simulate.network.delay=true
test.simulate.delay.ms=200

# Google Maps API
google.maps.api.key=YOUR_API_KEY_HERE
google.maps.enabled=true

# Default User Location
user.default.latitude=33.8886
user.default.longitude=35.4955

# Logging
logging.level.com.medmanager=DEBUG
pharmacy.network.enabled=true
google.drive.service.account.key=C:/Users/HP/Downloads/coherent-bay-490914-f1-025a3980afc2.json